#!/bin/bash
# Environment variables
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
export SHELL=/bin/zsh
export TERMINAL=/usr/local/bin/st
export ANDROID_HOME=~/Android/Sdk
export FLUTTER_HOME=~/flutter
export TMUX_PLUGIN_MANAGER_PATH=~/.tmux/plugins
export BORG_KEYS_DIR=~/.keys/borg
export BROWSER=firefox-developer-edition
export EDITOR=vim
export GOPATH=$HOME/go
export ANDROID_HOME=/home/yigit/Android

# Setup PATH
export CM_SYNC_PRIMARY_TO_CLIPBOARD=1
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$FLUTTER_HOME/bin
export DEFAULT_RECIPIENT="yigitcolakoglu@hotmail.com"
export PATH="$PATH:/home/yigit/.scripts:/home/yigit/.local/bin:/home/yigit/.gem/ruby/2.7.0/bin:$GOPATH/bin:$GOPATH/binexport:/home/yigit/.local/bin"
export CPATH=/usr/include/opencv4
