#!/bin/bash

# Set environment variables
export SSH_AUTH_SOCK
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
export SHELL=zsh
export TERMINAL=st
export ANDROID_HOME=~/Android/Sdk
export FLUTTER_HOME=~/flutter
export TMUX_PLUGIN_MANAGER_PATH=~/.tmux/plugins
export BORG_KEYS_DIR=~/.keys/borg
export BROWSER=~/.scripts/tabbed_surf
export EDITOR=vim

# Setup PATH
export PATH="~/.scripts/:~/.local/bin/:$PATH"
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$FLUTTER_HOME/bin

# Start X window manager
startx
