#!/bin/bash

# Environment variables
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
export SHELL=/bin/zsh
export TERMINAL=/usr/local/bin/st
export ANDROID_HOME=~/Android/Sdk
export FLUTTER_HOME=~/flutter
export TMUX_PLUGIN_MANAGER_PATH=~/.tmux/plugins
export BORG_KEYS_DIR=~/.keys/borg
export BROWSER="/home/yigit/.scripts/brave-start"
export EDITOR=vim
export GOPATH=$HOME/go
export ANDROID_HOME=/home/yigit/Android
export DEFAULT_RECIPIENT="yigitcolakoglu@hotmail.com"
#export CM_SYNC_PRIMARY_TO_CLIPBOARD=1

# Setup PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$FLUTTER_HOME/bin:$PATH
export PATH="/home/yigit/.scripts:/home/yigit/.local/bin:/home/yigit/.gem/ruby/2.7.0/bin:$GOPATH/bin:$GOPATH/binexport:/home/yigit/.local/bin:$PATH"
export CPATH=/usr/include/opencv4

# LF Icons
LF_ICONS=$(sed ~/.config/lf/diricons \
            -e '/^[ \t]*#/d'       \
            -e '/^[ \t]*$/d'       \
            -e 's/[ \t]\+/=/g'     \
            -e 's/$/ /')
LF_ICONS=${LF_ICONS//$'\n'/:}

export LF_ICONS
