#!/bin/bash


eval "$(grep -h -- \
	"^\s*\(export \)\?\(MBSYNCRC\|PASSWORD_STORE_DIR\|NOTMUCH_CONFIG\|GNUPGHOME\|XDG_DATA_HOME\|XDG_CONFIG_HOME\|XDG_RUNTIME_DIR\)=" \
	"$HOME/.profile" "$HOME/.bash_profile" "$HOME/.zprofile"  "$HOME/.config/zsh/.zprofile" "$HOME/.zshenv" \
	"$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.config/zsh/.zshrc" "$HOME/.pam_environment" 2>/dev/null)"

export NEXTCLOUD_USERNAME=yigitcolakoglu
export NEXTCLOUD_PASSWORD=$(pass show Server/drive.yigitcolakoglu.com/yigitcolakoglu)
export NEXTCLOUD_URL=https://drive.yigitcolakoglu.com/remote.php/webdav

declare -A mappings

mappings=(
  ["$NEXTCLOUD_URL/Documents"]="$HOME/Documents"
  ["$NEXTCLOUD_URL/Photos"]="$HOME/Pictures"
  ["$NEXTCLOUD_URL/InstantUpload"]="$HOME/Nextcloud/InstantUpload"
  ["$NEXTCLOUD_URL/Past Papers"]="$HOME/Nextcloud/Past Papers"
  ["$NEXTCLOUD_URL/InstantUpload"]="$HOME/Nextcloud/InstantUpload"
  ["$NEXTCLOUD_URL/University Applications"]="$HOME/Nextcloud/University Applications"
)


