#!/bin/bash

mcount=$(cat ~/.cache/mcount)
msync=$(cat ~/.cache/msync)

echo -n "^c#a3be8c^ ^d^ $msync ^c#81a1c1^ ^d^ $mcount"

case $BLOCK_BUTTON in
          1) setsid -f st -c center -n center -e neomutt;;
          1) ~/.local/share/scripts/mailsync;;
esac
