#!/usr/bin/zsh

alias feh="feh --scale-down --auto-zoom"
alias cclear="$(which clear)"
alias clear="clear && paleofetch"
alias neofetch="neofetch --ascii ~/.config/neofetch/ascii.txt"
alias open=xdg-open
alias rm="rm -i"
alias clip="xclip -selection clipboard"
alias g="git "
alias t="TERM=screen-256color-bce tmux"
alias tn="TERM=screen-256color-bce tmux new -s "
alias tat="TERM=screen-256color-bce tmux a  -t "
alias yain="yay -Syu "
alias ls="ls --color"
alias yay="yay --sudoloop"
alias lf=lf-ueberzug

# Suffix aliases
alias -g G=" | rg"
alias gshh="gcloud cloud-shell ssh --authorize-session"

# Git
alias ga="git add"
alias gcl="git clone --recursive"
alias gc="git commit"
alias gcm="git commit -m"
alias gp="git push"
alias gpall="git remote | xargs -I R git push R"
alias gpl="git pull"

# Homedir Cleanup
alias wget="wget --hsts-file=\"$XDG_CACHE_HOME/wget-hsts\""
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"

