/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_dwmblocks.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_systray.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "autostart.h"
#include "cyclelayouts.h"
#include "floatpos.h"
#include "fullscreen.h"
#include "movestack.h"
#include "pertag.h"
#include "scratchpad.h"
#include "shiftview.h"
#include "switchcol.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "winview.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"
