/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_dwmblocks.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_systray.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "autostart.c"
#include "cyclelayouts.c"
#include "floatpos.c"
#include "fullscreen.c"
#include "movestack.c"
#include "pertag.c"
#include "scratchpad.c"
#include "shiftview.c"
#include "switchcol.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "winview.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"
