#!/bin/sh


killprogs() {
	pkill -x udisks-glue
	pkill -x panel
	pkill -x redshift
}

logout() {
    pkill dwm
}

DMENU='dmenu  -z 1900 -x 10 -y 10 -i'

items="dwm
dwmblocks
mconnect
dunst
clipmenud"

# Open menu
selection=$(printf '%s' "$items" | $DMENU)

case $selection in
	dwm)
		touch /home/yigit/.cache/dwm-restart
		logout
		;;
	dwmblocks)
		kill -9 $(pidof dwmblocks)
		dwmblocks > /tmp/dwmblocks.out 2> /tmp/dwmblocks.err &
		;;
	mconnect)
		kill -9 $(pidof mconnect)
    (cd ~/Downloads/mconnect; mconnect -d > /tmp/mconnect 2> /tmp/mconnect.err &)
		;;
	clipmenud)
		pkill -f clipmenud
		clipmenud > /tmp/clipmenud.out 2> /tmp/clipmenud.err &
		;;
	dunst)
		kill -9 $(pidof dunst)
		dunst &
		;;
esac

exit
