#!/bin/bash
curl 'http://yeetclock/setcolor?R=2000&G=10&B=000&O=0'
/home/yigit/.scripts/pacontrol.sh open-mute
/home/yigit/.scripts/dunst_toggle.sh -s
betterlockscreen -l -t 'Stay the fuck out!'
/home/yigit/.scripts/dunst_toggle.sh -e
/home/yigit/.scripts/pacontrol.sh toggle-mute
curl 'http://yeetclock/setcolor?R=136&G=192&B=208'
