#!/bin/sh
#
# See the LICENSE file for copyright and license details. 
#

xidfile="$HOME/.surf/tabbed-surf.xid"
uri=""

if [ "$#" -gt 0 ];
then
	uri="$1"
fi

runtabbed() {
	if [ -z "$uri" ]
	then 
		tabbed -dn tabbed-surf -r 2 surf -e '' >"$xidfile" \
			2>/dev/null &
	else
		tabbed -dn tabbed-surf -r 2 surf -e '' "$uri" >"$xidfile" \
			2>/dev/null &
	fi
}

if [ ! -r "$xidfile" ];
then
	runtabbed
else
	xid=$(cat "$xidfile")
	xprop -id "$xid" >/dev/null 2>&1
	if [ $? -gt 0 ];
	then
		runtabbed
	else
		if [ -z "$uri" ]
		then 
			surf -e "$xid" >/dev/null 2>&1 &
		else
			surf -e "$xid" "$uri" >/dev/null 2>&1 &
		fi
	fi
fi

