#!/bin/bash

stats=$(<~/.cache/dunst)

if [ "$stats" = "off" ]; then
  echo "^c#88c0d0^ ^d^"
else
  echo "^c#88c0d0^ ^d^"
fi

case $BLOCK_BUTTON in
          1) ~/.scripts/dunst_toggle.sh -t;;
esac
