#!/usr/bin/zsh

alias feh="feh --scale-down --auto-zoom"
alias cclear="$(which clear)"
alias clear="clear && paleofetch"
alias neofetch="neofetch --ascii ~/.config/neofetch/ascii.txt"
alias idea="/home/yigit/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.7223.91/bin/idea.sh"
alias open=xdg-open
alias rm="rm -i"
alias clip="xclip -selection clipboard"
alias g="git "
alias t="TERM=screen-256color-bce tmux"
alias tn="TERM=screen-256color-bce tmux new -s "
alias tat="TERM=screen-256color-bce tmux a  -t "
alias yain="yay -Syu "
alias ls="ls --color"
alias yay="yay --sudoloop"

# Suffix aliases
alias -g G=" | rg" 
alias gshh="gcloud cloud-shell ssh --authorize-session"

# YeetClock
alias light="curl 'http://yeetclock/setcolor?R=136&G=192&B=208'"
alias lights_off="curl 'http://yeetclock/setcolor?R=2000&G=10&B=000&O=0'"

# Git
alias ga="git add"
alias gc="git commit"
alias gcm="git commit -m"
alias gp="git push"
alias gpall="git remote | xargs -L1 -I R git push R"
alias gpl="git pull"
